---
title: '2019-05-15'
author: "林茂廷"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

## colnames/ rownames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

只改col2的名稱
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2

```
 

改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2

```
```{r}

rownames(StuDF2)<-str_c("第",[1:5],"筆")
rownames(StuDF2)
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在(取代)
a[[5]] <- "7" # 元素不存在(新增)
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素2<-"hi"
b$新成員 <-c(2,5,1)
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
head(exData3)
```

```{r}
library(lubridate)
exData3$期間<-ymd(exData3$期間)
exData3

```

```{r}
isaisacrisis<-exData3$期間>=1997-06-01|exData3$期間<=1998-12-01
isaisacrisis
```
```{r}
exData3$isaisacrisis<-"True"
exData3

```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
head(transcriptDataFinal)
```
```{r}
logicalID<-transcriptDataFinal[[1]]=="92aS67fee" 
transcriptDataFinal$學號[logicalID]
```

```{r}
trys<-function(x,y){functionvalue<- x+y return(functionvalue)}
trys<-(2,3)
  
```
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}

