---
title: '2019-04-24'
author: "Pin-Chieh Chiu"
date: "4/24/2019"
output: html_document
---

```{r}
Mat1 <- matrix(c(1:6), 2,3)
Mat1
```

```{r}
class(Mat1)
typeof(Mat1)
```

```{r}
Mat2 <- matrix( c("a","b","c","d"), 2, 2)
Mat2
Mat2[2]
Mat2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF
StuDF[[2]][[3]]
```

```{r}
class(StuDF)
typeof(StuDF)
StuDF[[2]][[3]]
```

```{r}
class(StuDF$姓名)
```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
class(StuList)
```

```{r}
as.data.frame(StuList) -> StuDF3
class(StuDF3)
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
LETTERS
```

```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
chosenLETTERS[8]
matObj1[8]
```

```{r}
matObj1
```

```{r}
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
matObj1[c(1,4),c(2,3)]
matObj1[c(T,F,F,T,F),c(F,T,T)]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
classSurvey[,4:5]
classSurvey[,c(4,5)]
classSurvey[,c(F,F,F,T,T,F)]
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

