---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019 billpractice"
output: html_document
---
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
StuDF[["姓名"]][[3]]
```

```{r}
class(StuDF$姓名)
```
```{r}
StuDF$姓名<-as.character(StuDF$姓名)
class(StuDF$姓名)
```


```{r}
StuDF[1,2]
StuDF[,2]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList

as.data.frame(StuList) -> StuDF3

StuDF3

```
```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
StuDF4

```
```{r}
chosenLETTERS <- LETTERS[1:20]
matObj1 <- matrix(chosenLETTERS,4,5)
matObj1
```

```{r}
matObj1[1,]
```

```{r}
matObj1[c(T,F,F,T),c(F,T,T,F,F)]
theletter<-matObj1[3,2]
tolower(theletter)
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")

```
```{r}
classSurvey[,3]
```

```{r}
classSurvey[c(1:60),c(4,5)]
```
```{r}
classSurvey[c(T),c(4:5)]
```

