---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}

dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")

```

```{r}
aLogical <- c(T,TRUE,F,FALSE,TRUE)
class(aLogical)

```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)

```



#factor

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
studentMajors0 <- 
  c("經濟系", "經濟系", "法律系")

```
```{r}
class(studentMajors)
```
```{r}
class(studentMajors0)
```



```{r}
typeof(studentMajors)
```
```{r}
typeof(studentMajors0)
```

```{r}
as.integer(studentMajors)
```

##

```{r}
birthplace <- factor(
  c("台北市","高雄市","台中市","高雄市","台北市")
)

class(birthplace)
levels(birthplace)
as.integer(birthplace)
```


#lubridate

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```
```{r}
typeof(dtObject)
```

##
```{r}
library(lubridate)
dtObject<-ymd_hms("2019-03-20 16:58:53") 
dtObject<-ymd_hms(c("2019-03-20 16:58:53"))
class(dtObject)
typeof(dtObject)
as.double(dtObject)
```


