---
title: '0522'
author: "張淳森"
date: "2019年5月22日"
output: html_document
---


請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
library(lubridate)
NYtimeex <- ymd_hms("1973-02-21 12:05:22", tz="America/New_York")
NYtimeexchange <- with_tz(NYtimeex, tzone="Asia/Taipei")
NYtimeexchange

TimeFun <- function(NYtimeex){
  NYtimeex <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
  NYtimeexchange <- with_tz(NYtimeex, tzone="Asia/Taipei")
  rerun(NYtimeexchange)
}                                                                    #這個作法只有output "一個"
```

```{r}
ymd_hms_function <- function(input, fromTzone, toTzone){
  step1 <- ymd_hms(input, tz=fromTzone)
  answer <- with_tz( ymd_hms(input, tz=fromTzone), tzone =  toTzone)
  return(answer)
}

ymd_hms_function("1998-10-10 23:45:53", "Asia/Taipei", "America/New_York")
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```

```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911  # (?<=(民國))[:digit:]+ <- 取出一串數字們 前接民國
mm<-str_extract(twDates,"[:digit:]+(?=月)")  #[:digit:]+(?=月) <- 取出一串數字們 後面接月
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```

```{r}
yyyymmddtimefun <- function(twDates){
 yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911  
 mm<-str_extract(twDates,"[:digit:]+(?=月)")  
 yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-")) 
 return(yyyymmdd)
}

yyyymmddtimefun("民國87年10月")
```

```{r}
yyyymmddtimefun <- function(twDates,dd="10"){        
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911  
  mm<-str_extract(twDates,"[:digit:]+(?=月)")  
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-")) 
  return(yyyymmdd)
}
yyyymmddtimefun("民國87年10月10日")
```






