---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---
```{r}
bVector<-c("你好","How are you?")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
b<-"你好"
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```
```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
typeof(studentMajors)
```
```{r}
levels(studentMajors)
```
```{r}
studentMajors
```
```{r}
as.integer(studentMajors)
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```
```{r}
birthplace <- factor(
  c("台中市","台北市","台中市","台北市","台中市")
)
```
```{r}
class(birthplace)
```
```{r}
levels(birthplace)
```
```{r}
as.integer(birthplace)
```
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
class(dtObject)
```
```{r}
typeof(dtObject)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

# Logicals

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

# Factor

```{r}
studentMajors0 <- c("經濟系", "經濟系", "法律系")
```


```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
class(studentMajors0)
```

```{r}
class(studentMajors)
```

```{r}
studentMajors0
```

```{r}
studentMajors
```

```{r}
typeof(studentMajors)
```


```{r}
typeof(studentMajors0)
```

```{r}
levels(studentMajors)
```

```{r}
as.integer(studentMajors)
```

```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace)
```

```{r}
birthplace <- factor(
  c("台北市","台北市","台中市","台北市","台中市")
)
class(birthplace)
levels(birthplace)
as.integer(birthplace)
```


```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```


```{r}
stringInteger
trueInteger
```

# Date Time

```{r}
library(lubridate)
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```


```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
typeof(dtObject)
```

```{r}
as.integer(dtObject)
```

# Time zone

```{r}
Sys.timezone()
```


```{r}
libaray(lubridate)
```
```{r}

twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime

```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime

```
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```
```{r}
a+b
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```
```{r}
class(aL)
```
```{r}
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:00:00", tz="Asia/Taipei")
```

```{r}
twDateTime2 <- ymd_hms("2019-03-20 14:00:00", tz="Asia/Taipei")
```
```{r}
twDateTime2-twDateTime
```

```{r}
as.integer(twDateTime2-twDateTime)
```
```{r}
startingDate <- ymd("2000-02-17")
```
```{r}
startingDate + years(1)
```
```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
x <- 5
y <- 7
```
```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```
```{r}
x2
y2
x2<y2
```
```{r}
x2
x2>4

```
```{r}
y2
y2==y2
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```
```{r}
x3
y3
x3==y3

```
```{r}
x3
y3
x3!=y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```
```{r}
is.na(x2)


