---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```
```{r}
sum(aLogical)
```
```{r}
bLogical <- c(T,T,T,F)
class(bLogical)
```
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```



```{r}
as.integer(studentMajors)
```

```{r}
typeof(studentMajors)
```

```{r}
studentMajors0 <- c("經濟系", "經濟系", "法律系")
```
```{r}
typeof(studentMajors0)
```

```{r}
born <- factor(c ("台北","台北","台中","台中","台中"))
```

```{r}
born <- factor(c ("台北","台北","台中","台中","台中"))
levels(born)
as.integer(born)
class(born)
```
```{r}
library(lubridate)
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
class(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
typeof(dtObject)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
typeof(dtObject)
as.double(dtObject)

```

