---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course ,"經濟學")
```
detect 是告訴你True or False
```{r}
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```

```{r}
str_sub(studentID,5,6)
```
第一個數字是開始，第二個數字是結束
```{r}
year <- str_sub(studentID,2,4)
year
major <- str_sub(studentID,5,6)
major
```
str_c 是把字串起來
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
也可以只打一個向量
```{r}
str_c(month,c("月"),day,c("日"))
```
也可以單打一個字
```{r}
str_c(month,"月",day,"日")
```
sep="某符號" 是分隔符號的意思
```{r}
month
day
str_c(month,day, sep="-")
```

```{r}
pp <- c("^","-","=")
qq <- c("-","-","=")
pp
qq
str_c(pp,qq,sep = "_")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
```
replace有2個的話要打all不然只有前面一個
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
str_c("https://github.com",username,reponame,sep = "/")
```
練習1
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
date01 <- str_sub(birthday,1,4)
date02 <- str_sub(birthday,5,6)
date03 <- str_sub(birthday,7,8)
birthday02 <- str_c("西元",date01,"年",date02,"月",date03,"日")
birthday02
```
練習2
```{r}
library(lubridate)
```

```{r}
民國年月<-c("099/01","099/02","099/03")
```
```{r}
year01 <- c(099)
as.integer(year01)
month01 <- c(01,02,03)
year02 <- year01+1911
as.character(year02)
str_c(year02,month01,sep = "/")

```
```{r}
民國年月<-c("099/01","099/02","099/03")
y<- str_sub(民國年月,2,3)
m<- str_sub(民國年月,5,6)
y2<- as.integer(y)
m2<- as.integer(m)
str_c("西元",y2+1911,"年",m2,"月")
```

