---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
```
```{r}
str_detect(course,"經濟學")
```
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```
```{r}
str_sub(studentID,5,6)
```
```{r}
str_sub(studentID,2,4)
```
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```
```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```
```{r}
month
day
str_c(month,day, sep="-")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```
```{r}
dates
str_replace(dates,"-","月")
```
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```


```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame, sep="/")
```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
head(birthday)
year<-str_sub(birthday,1,4)
month<-str_sub(birthday,5,6)
date<-str_sub(birthday,7,8)
bday<-str_c("西元",year,"年",month,"月",date,"日")
bday
```
```{r}
chineseyear<-str_sub(民國年月,2,3)
chineseyear
chineseyear<-as.numeric(chineseyear)
year1<-chineseyear+1911
year1
month1<-str_sub(民國年月,5,6)
answer<-str_c("西元",year1,"年",month1,"月")
answer
```
#Vectors
```{r}
a<-c(1:3)
typeof(a)
a
```
```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```
```{r}
b1<-list("a","b",c(1:10), TRUE)
typeof(b1)
b1
```
```{r}
b2<-list(
  第一個="a",
  第二個="b",
  第三個=c(1:10))
b1
b2
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```



```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
成績單[["個經"]]
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```
```{r}
studentRecord[["姓名"]]
```
```{r}
studentRecord[["學年平均成績"]][[3]]
```
```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
```
```{r}
plasticContainer

extract1 <- plasticContainer[c("greenBox")]
extract1
extract2 <- plasticContainer[[c("greenBox")]]
extract2
```
```{r}
extract1[[1]][[1]]
extract2[[1]]
```
```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```
```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```
```{r}
your_github_username <- "tpemartin"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```
```{r}
commitCheckStatement
```
```{r}
commitCheck[[4]][["commit"]][["committer"]][["date"]]
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```
```{r}
filmVotingData$Timestamp
filmVotingData[["Timestamp"]]
```

```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
```
```{r}
favoriteTwo[logiCorrect] -> validFavoriteTwo
validFavoriteTwo
```











