---
title: 'timepractice'
author: "林茂廷"
date: "3/13/2019"
output: html_document
---

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
dtObject1<-ymd_hms("1999-02-01 00:00:00")
```

```{r}
dtObjectVector1<-ymd_hms(c("1999-02-01 00:00:00","2004-08-05 00:00:00"))
```

```{r}
class(dtObject)
class(dtObject1)
class(dtObjectVector)
class(dtObjectVector1)
```

```{r}
dtObject
dtObject1
```
```{r}
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
RomeDateTime <- with_tz(twDateTime,tzone="Europe/Rome")
tokyoDateTime <- with_tz(twDateTime,tzone="Asia/Tokyo")
bangkokDateTime <- with_tz(twDateTime,tzone="Asia/Bangkok")
```
```{r}
ymd("20190330")
ymd("2018-09-11")
mdy("March 3, 2019")
```
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
as.integer(ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei"))
as.integer(ymd_hms(LisbonDateTime))
as.integer(ymd_hms(tokyoDateTime))
as.integer(ymd_hms(bangkokDateTime))
```
```{r}
class(twDateTime)
```
```{r}
class(LisbonDateTime)
```
```{r}
class(RomeDateTime)
```

