---
title: '2019-05-15'
author: 410473076
date: "5/15/2019"
output: html_document
---

#7.5
```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```



#7.6
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]] <- FALSE
b[[5]] <- 7
b
```


#使用"元素名稱"創新元素
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```


#example

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))

```

取出「期間」變數轉成date class。
```{r}
library(lubridate)
exData3[[1]] <- ymd(exData3[[1]])
class(exData3[[1]])
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
exData30
```


增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）。
```{r}
exData3$isAsiaCrisis <- (exData3$期間>=ymd("1997-06-01"))&(exData3$期間<=ymd("1998-12-01"))
class(exData3$isAsiaCrisis)
exData3
```



利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本。
```{r}

```






