---
title: '2015-05-22'
author: "張舒涵"
date: "5/22/2019"
output: html_document
---


## midterm 6.2

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"

```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical
invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical
library(lubridate)
ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York") -> nyDateTime
invoiceList$UTC時間[nyLogical] <-
  with_tz(nyDateTime,tzone="UTC")
ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei") -> tpDateTime
invoiceList$UTC時間[tpLogical] <-
  with_tz(tpDateTime,tzone="UTC")
invoiceList 
```




```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],
        tz="America/New_York") -> nyDateTime

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],
        tz="Asia/Taipei") -> tpDateTime

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```




#請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  ymd_hms(input,tz=fromTzone) -> fromDateTime 
  with_tz(fromDateTime,tz=toTzone) ->toDateTime
  return(toDateTime) 
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(lubridate)
fromTzone <- ymd_hms("1973-02-21 12:05:22", tz="America/New_York")
toTzone <- with_tz(utctime1,tzone = "Asia/Taipei")

ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input, tzone = fromTzone)
  answer <- with_tz(time1,tzone = toTzone)

  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```


#8.1.2

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```

```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```



#原始步驟
```{r}
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd
```
#寫成函數
```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
```












