---
title: '2019-05-15 billpractice'
author: "林茂廷"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

## colnames/ rownames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

只改col2的名稱
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2

```
 

改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2

```
```{r}
colnames(StuDF)[c(1,3)]<-c("三碼","分數")
StuDF
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]]<-FALSE
b[[5]]<-7
b
```

```{r}
b$元素2<-"object"
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
class(exData3$期間)
```

```{r}
exData3$期間<-ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis<-(ymd(exData3$期間)>="1997-06-01"&ymd(exData3$期間)<='1998-12-01')
exData3
```
```{r}
front <- ymd("1997-06-01")
end <- ymd("1998-12-01")
isAsiaCrisis <- exData3$期間 >= front & exData3$期間<= end
#isAsiaCrisis
"子樣本" <- exData3$期間[isAsiaCrisis]
子樣本
#sum(isAsiaCrisis)
```
```{r}
exData3[exData3$isAsiaCrisis==TRUE,]
exData3[exData3$isAsiaCrisis,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
transcriptDataFinal[transcriptDataFinal$學號=="92aS67fee",]
```
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```
```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
ttt<-function(w,x,y,z){tttvalue<-w^x+x^1/2/(y+z)
return(tttvalue)}
```

```{r}
ttt(2.4,5.8,7.4,8.3)
```

```{r}
supply_fun <- function(a,b,P){
Qs <- a+b*P # 程序產生output值
  return(Qs) # 傳回output值
}
demand_fun <- function(c,d,P){
Qd <- c-d*P # 程序產生output值
  return(Qd) # 傳回output值
}
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical
invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],
        tz="America/New_York") -> nyDateTime
invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")
ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],
        tz="Asia/Taipei") -> tpDateTime
invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent

subSample <- transcriptDataFinal[logiChosenStudent,]

sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun("d55S6d052")
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
twDates
```

```{r}
date_convert_twYM <- function(x){
  yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(x,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
return(yyyymmdd)
}
date_convert_twYM(twDates)
```

```{r}
date_convert_twYM("民國102年9月")
```

```{r}
date_convert_twYM <- function(twdate, day=01){
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911 
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,day,sep="-"))

  return(yyyymmdd)
}

date_convert_twYM("民國108年5月")
date_convert_twYM(twDates, 04)
```

```{r}

```

