```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
plasticContainer[["greenBox"]][1]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)

成績單[[1]]
成績單[["個經"]]
```

```{r}
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]

```

```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
```

```{r}
extract1 <- plasticContainer[c("greenBox")]
extract1[[1]][[1]]

extract2 <- plasticContainer[[c("greenBox")]]
extract2[[1]]
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```



```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList
unlist(favoriteTwoList) -> allVotes
table(allVotes) 
```

```{r}
logicorrect<-str_length(birthday)==8
logicorrect
```








