---
title: '2019-03-20'
author: "2019-03-27 billpractice"
date: "3/20/2019"
output: html_document
---

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
a+b
```

```{r}
a*b
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```


```{r}
class(aL)
```

```{r}
class(aL*bL)
```

```{r}
c <- 4

c+a
```

```{r}
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
twDateTime2 <- ymd_hms("2019-03-11 14:08:00", tz="Asia/Taipei")
```

```{r}
twDateTime-twDateTime2
```
```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```
```{r}
startingDate + dyears(1)
```

```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7
```

```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
is.na(x2)
```
```{r}
0/0
```
```{r}
x2==y2
```
```{r}
sum(x4)
```


