---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
studentMajors <- factor(
  c("經濟系", "不動系", "法律系")
)
```

```{r}
typeof(studentMajors)
```
```{r}
levels(studentMajors)
```

```{r}
hometown <- factor(
  c("台中","台北","台北","台中","台北")
)
typeof(hometown)
levels(hometown)
as.integer(hometown)
```



```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
JaponDateTime <- with_tz(twDateTime,tzone="Asia/Jaipon")
typeof(twDateTime)
as.double(twDateTime)
as.double(JaponDateTime)
as.integer(twDateTime)
Nowdatetime <- mdy_hms("3/14/2019_15:51:00")
```



```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+b
a+bL
aL+bL
class(a+bL)
class(aL+bL)
```

```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x3 <- c("小明","小花")
y3 <- c("小明","小華")

x == y
x <= y
x != y
x < y

x2 == y2
x2 >= y2
x2 != y2
x2 <= y2

x3 == y3
x3 != y3
```
! negation
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
x3 != y3
!(x3 == y3)
!(x3 != y3)
```


```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

is.na(x2)
is.na(y2)
```
















































