---
title: '2019-04-17'
author: "林茂廷"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```

```{r}
a<-c(1:3)
typeof(a)
a
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
plasticContainer[["greenBox"]][[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[[1]]
```
```{r}
studentRecord[["姓名"]]
studentRecord[[4]][[3]]
```
```{r}
extract1 <- plasticContainer[c("greenBox")]
extract1[[1]][[1]]
extract2 <- plasticContainer[[c("greenBox")]]
extract2[[1]]
```


```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
your_github_username <- "tpemartin"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"="95226",
    ":repo"="107-2-inclass-practice"
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
committwtime <- commitCheck[[4]][[3]][[2]][[3]]
class(commitCheck[[4]][[3]][[2]][[3]])
committwtime <- ymd_hms(committwtime)
class(committwtime)
Sys.timezone()
twTime <- with_tz(committwtime,tzone="Asia/Taipei")
twTime
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```




```{r}
str_length(birthday) == 8 
logiCorrect <- str_length(birthday) == 8
favoriteTwo[logiCorrect] -> valueFavoritetwo
valueFavoritetwo
```


```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList
StuList[[2]][3]
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
StuDF[["姓名"]][[3]]
```


```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```


```{r}
as.data.frame(StuList) -> StuDF3
class(StuDF3)
```
```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```


```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```


```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
Vector1[["名稱4"]]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
StuList 

```



```{r}
StuDF
StuDF[c("姓名","成績")] 
StuDF[1:5,c("姓名","成績")] 
```

```{r}
StuDF[,c("姓名","成績")]
```

```{r}
colnames(StuDF) 
rownames(StuDF)
```


```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]] <- FALSE
b[[5]] <- "7"
b
```

```{r}
a <-as.double(ymd("1997-06-01"))
b <-as.double(ymd("1998-12-01"))
dou <- as.double(exData3$期間) 
isAsiaCrisis <- (dou-a) >=0 & (b-dou)>=0
isAsiaCrisis
exData3[isAsiaCrisis,]
```


```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
exData3
```

```{r}
exData3[["isAsiaCrisis"]] <- (exData3$期間 >= "1997-06-01" & exData3$期間 <= "1998-12-01")
exData3
```


```{r}
as.double(exData3$期間)->a
as.double(1997-06-01)<=a&a<=as.double(1998-12-01)->exData3$isAsiaCrisis
```


```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
log<-transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[log,]
```


```{r}
function1 <- function(x, .alpha){
  functionvalue <- x+.alpha
  return(functionvalue)
}

class(function1)
function1(2,4)
```





























