---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```
```{r}
bVector<-c("你好","How are you?")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)

sum(aLogical)
```

#factor

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
studentMajors
```

```{r}
studentMajors1<- 
  c("經濟系", "經濟系", "法律系")
```
```{r}
studentMajors1
```
```{r}
typeof(studentMajors1)
```
  

```{r}
typeof(studentMajors)

```

```{r}
levels(studentMajors)
```
##### 法律系是1 經濟系是2
```{r}
studentMajors
```

```{r}
as.integer(studentMajors)
```
#####等於 經濟 經濟 法律
```{r}
birthplace<-factor(c("台北" ,"台中" ,"台中"))
typeof(birthplace)
```
```{r}
levels(birthplace)
```
```{r}
as.integer((birthplace))
```

```{R}
stringInteger <- c("1","2","-11")
class(stringInteger) 
```
#####是文字不能計算
```{R}
trueInteger <- as.integer(stringInteger)
class(trueInteger) 
```
#####可以運算

##### 安裝lubridate 來計算時間
```{R}
library(lubridate)
```
```{R}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{R}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{R}
class(dtObject)
```
######系統成功讀成時間
```{r}
dtObject
```
###要先把時間轉成utc
```{r}
typeof(dtObject)
as.double(dtObject)
```
