---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
b<-"你好"
bVector<-c("你好","How are you?")
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
## 小明說："明天不用上課。"
## 小花說："真的嗎？"
```

# factor

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)

studentMajors0 <- c("經濟系", "經濟系", "法律系")


birthplaces <- factor(c("雲林縣","古坑鄉","高林村"))
class(birthplaces)
levels(birthplaces)
as.integer(birthplaces)
```
```{r}
library(lubridate)

dtObject<-ymd_hms("1970-01-01 00:02:53") 

dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

class(dtObject)

dtObject
```



```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime

```


```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
as.integer(twDateTime)
```
```{r}
now <- mdy_hms("03-27-2019 15:49:38")

now
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)

a+b
aL+bL
a+bL

a/4
a+1
a*2
a%%5
a**b
```
```{r}
twDateTime
twDateTime+999
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```





